### PR TITLE
Update RealPlume.netkan

### PR DESCRIPTION
**Pull request by politas**
Need to bump the epoch to support the change from 0.4.x to 10.4.x

### CODE REVIEW

**Comment by politas** [comment]
Also, has this been tested on 1.0.5, yet? If it works, ksp_version should be replaced with a range of ksp_version_min 1.0.4 to ksp_version_max 1.0.5

**Comment by NathanKell** [comment]
It works on 1.0.5 just fine.

**Comment by politas** [comment]
Ok, if you merge this, CKAN will start handling RealPlume correctly for 1.0.5 users.

**Comment by politas** [comment]
Thanks.

**Pull request merged**
