### PR TITLE
RealPlume smoke performance rebalance

### PR DESCRIPTION
**Pull request by stratochief66**
Reduce the particle creation and lifetime for some engines.

Improves performance of RealPlume by keeping a lower control value of smoke particle creation and lifetime.

### CODE REVIEW

**Comment by NathanKell** [comment]
@Felger assuming this is ok with you, I'm inclined to merge and roll a release to tide us over (@sarbian says things may be much better in Unity 5 / KSP 1.1.)

**Comment by Felger** [comment]
Yeah, this looks good.  Assuming it can wait that long, I'll have some time this weekend to push out a release for 1.0.5 for all my mods.

**Comment by NathanKell** [comment]
Makes sense. Also, there's a bit of an issue between AJE and RealPlume that could use a look, IIRC. @blowfishpro ?

**Comment by stratochief66** [comment]
@NathanKell 
@Felger 

Nothing ever happened with this? Lol.

**Comment by Felger** [comment]
Someone really needs to get on that @Felger guy to get off his butt and merge this PR.

**Pull request merged**
