### PR TITLE
Added Vacuum Expansion to Hydrolox_LowerBlaze

### PR DESCRIPTION
**Pull request by Chandra-Aerospace**
Added Vacuum Expansion to the Blaze component of Hydrolox_LowerBlaze

### CODE REVIEW

**Comment by zorg2044** [comment]
Hmm ill take a look when I have a little time to test properly but generally im not a huge fan of how the flamey "blaze" effects from the PlumeParty blueorigin library look when expanded. This was why I faded it out for this plume.

I actually favour the more subtle cryoengines based sea level plumes for cryo SL lifters. I actually switched everything I originally configured using this to those plumes. But I guess this can function as a less realistic plume for people who like some pazzaz.

**Comment by zorg2044** [comment]
So I took a look at your changes and I personally think the better approach is to make the flames even more transparent at start and not include it in expansion effects which I might do.

But even putting any possible changes aside the more I think about it the more I wish I hadn't added this plume in. I developed this based on existing plume party fx but before I started working with cryo engines fx. The problem with this is its far too colourful and has too much going on for a hydrolox plume. Its kind of similar to some of the older colourful LH2 plumes.

I get that you personally like this, however as I try to make expanded plumes more transparent, add more realism (such as with upcoming kerolox plumes), this particular plume is something that goes in the complete opposite direction of where I want to take real plume. I am seriously considering removing it entirely (since its not used in RealPlume-stock except for the Rhino but I'm changing that next update) and I dont think a lot of configs have been written for it.  

But for now I have moved it into a deprecated folder along with various old stuff which is not being removed but people are being discouraged from adding to new engines.

**Comment by Chandra-Aerospace** [comment]
Sounds Good to me! Do you think you could do a Solid-Lower overhaul With ReStock SRB FX?

**Comment by zorg2044** [comment]
Hmm I'll take a look at it. Generally I avoid revamping existing plumes because its hard to make a change that wouldnt require existing configs to be adjusted. 

Not entirely sure a new SRB plume is worth it without new smoke effects and I wrote on the thread regarding the challenges surrounding making new smoke effects. Still I will consider it.

A new solid vacuum plume based on PlumeParty or ReStock fx is a bit more likely. Anyway lots of things to consider :)

**Pull request closed without merging**
