### PR TITLE
SpaceY-Lifters Engines

### PR DESCRIPTION
**Pull request by Nhawks1717**
Not all of them but at least have some done. Will finish the last few
tomorrow.

### CODE REVIEW

**Comment by Shurichan** [comment]
Are SpaceY engines working with RO?

**Comment by NathanKell** [comment]
@Shurikeeen  they're not, yet, but this is to the RealPlume-Stock folder. :)

**Comment by NathanKell** [comment]
I'll let @Felger look these over when he gets a chance rather than merging when I don't know the details....

**Comment by Nhawks1717** [comment]
Yeah sorry, I didn't know this was also the actual RO git, should've specified in my commit!

**Comment by Felger** [comment]
In retrospect, I should have let @NathanKell know I was keeping all the RealPlume configs in one place, including RealPlume-Stock.  Oops.

**Comment by NathanKell** [comment]
Nono. that's fine, that I figured out. It's just I'm not good enough with PLUME nodes to feel comfortable reviewing the PR. :)

**Pull request merged**
