### PR TITLE
Add cryogenic engine plume config

### PR DESCRIPTION
**Pull request by Nhawks1717**
Added multi-purpose cryogenic plume effect using Nertea's cryogenic
effects added awhile ago.

### CODE REVIEW

**Comment by Nhawks1717** [comment]
Would prefer someone possibly looking over this before merging to the master branch, let me know if you see anything wrong with it or go ahead and merge it yourself. Thanks!

Here's some pictures for you to look at
screenshot3
screenshot5
screenshot6

**Comment by jjeffhendryx** [comment]
I really like it!

**Comment by stratochief66** [comment]
The pictures look nice, just not very descriptive. Are those set to different altitudes, or throttles?

Which engines were you thinking of attaching these to?

I'd want to test it in game before merging it myself, it looks pretty though.

**Comment by Nhawks1717** [comment]
It's tied to atmosphere level like all the other plumes. I myself will be adding them to the Cryogenic engines mod by Nertea which is where the effects come from. Anyone else can attach them to whatever they want.

**Comment by Nhawks1717** [comment]
Added remaining cryogenic effects and renamed the -1 plume to -125 to signify it should be used with 1.25m engines. I'll give this a couple of days for anyone to look at and make comments on before I merge it myself (if someone doesn't do it by then).

**Pull request merged**
